### ISSUE TITLE
Hello schulzefelix, Config 

### ISSUE THREAD

**Issue by thinha** [schulzefelix/laravel-search-console#14]
I have the service_account.json file. 

Into: Config/search-console, At: Connections  i get path of file json.

And have error: 
Unable to read the credential file specified by GOOGLE_APPLICATION_CREDENTIALS: file laravel-search-console does not exist.

I have added account to google webmaster tool ?

Please help me, thank you !

**Comment by schulzefelix** [comment]
Hey, are you sure if the path to file is correct?
But tbh I mostly using it with oauth option as connection. Can you share your config file to have a look?
