### ISSUE TITLE
List Sitemaps

### ISSUE THREAD

**Issue by seoanalyze** [schulzefelix/laravel-search-console#15]
Hey, first at all: Thank you for your great package. It's very useful for my application.

But I'm having problems to list all sitemaps of a specific URL.
Is it possible with your search-console package to crawl this informations?

Thank you! :)

**Comment by schulzefelix** [comment]
Hey, it's possible, but I did not implements all API methods into this package. You can use the underlying service to call all API methods directly and transform the response as you like.

For example:
```$sitemapService = SearchConsole::setAccessToken($token_array)->getWebmastersService()->sitemaps;

    $data = $sitemapService->listSitemaps('https://www.expedia.de');

    foreach ($data->getSitemap() as $wmxSitemap) {
        dd($wmxSitemap);
    }
```

You will find all methods here: https://developers.google.com/webmaster-tools/search-console-api-original/v3/sitemaps
