### ISSUE TITLE
file_exists should be an absolute path

### ISSUE THREAD

**Issue by Globerada** [schulzefelix/laravel-search-console#21]
Hi. First of all, thank you for this awesome package!

I am using with a **GOOGLE_AUTH_TYPE=service_account**, so I need to put my credentials as a .json.

The package must be modified so it works under all circumstances: commands, test, and calling from a route.

For instance, if we have:
**GOOGLE_APPLICATION_CREDENTIALS=search-console-credentials.json**

When calling via a controller web this would fail, because file_exists in guardAgainstInvalidConfiguration is checking relative to public path.

We can use helper function [base_path()](https://laravel.com/docs/master/helpers#method-base-path) to grab the correct file.

**Comment by Globerada** [comment]
What do you think about using base_path or storage_path in config.php as Laravel Analytics of Spatie does? In that case, no change would be necessary, only maybe update a bit of docs.

https://github.com/spatie/laravel-analytics/blob/master/config/analytics.php

**Comment by schulzefelix** [comment]
Changed the default recommendation to using storage_path in 1.5.0.
