### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by spekulatius** [schulzefelix/laravel-search-console#23]
Hello @schulzefelix 

I was wondering if you aware of any options/ways to sort the returned information. I'd like to ensure not asking large chunks of data only to sort them out on my end. I've not been able to find anything in the Googel docs. Any suggestions or ideas?

Viele Grüße,
Peter

**Comment by schulzefelix** [comment]
Hey, sorry for the late answer. I think I had the same issue, when I wrote this package, if its not in the API, then they still don't provide it and you have to order it by yourself at the end.

**Comment by spekulatius** [comment]
Yeah, okay, fair enough. Just raised it to see if you maybe know more :+1:
