### ISSUE TITLE
how can we set the datastate using this package?

### ISSUE THREAD

**Issue by vesper8** [schulzefelix/laravel-search-console#28]
I want to change the datastate to `all` as explained here https://searchengineland.com/google-search-console-api-gains-fresh-data-more-344552

In order to retrieve fresh data that is less than 1 day old.

The current default does not return this fresh data when I use this package.

I can see that there's a `setDatastate` function on both `Google_Service_Webmasters_SearchAnalyticsQueryRequest` and `Google_Service_SearchConsole_SearchAnalyticsQueryRequest` but I can't figure out how to change it using this package.

This is my current code

```
        $site = 'sc-domain:mydomain.com';

        $searchConsole = app(SearchConsole::class);

        putenv(sprintf('GOOGLE_APPLICATION_CREDENTIALS=%s', config('search-console.connections.service_account.application_credentials')));

        $period = Period::create(Carbon::now()->subDays(30), Carbon::now());

        $dimensions = [
            'date',
        ];

        $performanceData = $searchConsole->searchAnalyticsQuery($site, $period, $dimensions);

```

Any help appreciated

**Comment by vesper8** [comment]
So it seems like adding `$request->setDataState('all');` inside your `searchAnalyticsQuery` function does the trick

But I don't know if it's possible to modify this without forking/changing the base code.. it doesn't look like it is

**Comment by vesper8** [comment]
I've created a PR to add this functionality https://github.com/schulzefelix/laravel-search-console/pull/29

If that optional parameter is not passed then the behaviour will be the same as it currently is

**Comment by schulzefelix** [comment]
Thanks a lot! Merged the PR. I added it also in the response object and updated the readme.

-> v1.7.0
