### ISSUE TITLE
Service account 

### ISSUE THREAD

**Issue by stevewolfe555** [schulzefelix/laravel-search-console#31]
Hello,

Does the service account option work with searchAnalyticsQuery I can seem to list all sites but its not showing as authenticated.

**Comment by schulzefelix** [comment]
Sorry can't help you with that, I always used it with the oauth method.

Feel free to investigate and submit a PR.

**Comment by RhysLees** [comment]
> Does the service account option work with searchAnalyticsQuery I can seem to list all sites but its not showing as authenticated.

You need to add your service account as an owner to each of the sites in the search console first
