### ISSUE TITLE
Non static method 'setAccessToken()' could not be called statically

### ISSUE THREAD

**Issue by RhysLees** [schulzefelix/laravel-search-console#32]
When i use:

$sites = SearchConsole::setAccessToken($token)->listSites();
return $sites;

i get the following error:
Non-static method SchulzeFelix\SearchConsole\SearchConsole::setAccessToken() cannot be called statically

**Comment by RhysLees** [comment]
I can not call it non-static either as its construct method requires "SearchConsoleClient $client"

**Comment by schulzefelix** [comment]
I guess you missing the 

use SearchConsole;

statement in your class

**Comment by RhysLees** [comment]
> I guess you missing the
> 
> use SearchConsole;
> 
> statement in your class

nope, its included, SearchConsole::setAccessToken()  is not a stactic method 

```
 /**
     * @param string|array $accessToken
     *
     * @return $this
     */
    public function setAccessToken($accessToken)
    {
      ....
    }
```

should be

```
 /**
     * @param string|array $accessToken
     *
     * @return $this
     */
    public static function setAccessToken($accessToken)
    {
      ....
    }
```

**Comment by kingzamzon** [comment]
@RhysLees any solution on this issue??
am currently stuck here

**Comment by RhysLees** [comment]
@kingzamzon the only thing I can suggest is to fork the repo and make the change above

**Comment by kingzamzon** [comment]
@RhysLees I made the changes but got more error on my end..
do you have a fork?

**Comment by RhysLees** [comment]
> @RhysLees I made the changes but got more error on my end..
> do you have a fork?

No sorry

**Comment by kingzamzon** [comment]
How were you able to sort yours out?

**Comment by RhysLees** [comment]
> How were you able to sort yours out?

Just didn't use this package. I used a spatie package instead

**Comment by schulzefelix** [comment]
Hi,
it definitely works with `use SearchConsole;` like the last 5 years.

**NOT** "use SchulzeFelix\SearchConsole\SearchConsole;"!

![image](https://user-images.githubusercontent.com/8378750/157903921-285c2031-9009-40d2-9ab3-c09ad6c9bf6d.png)

@RhysLees Which Spatie package you using for the SearchConsole?
