### ISSUE TITLE
Can we access new URL Inspection API with this package?

### ISSUE THREAD

**Issue by iamprageeth** [schulzefelix/laravel-search-console#36]
Refer :
https://developers.google.com/webmaster-tools/v1/urlInspection.index/urlInspection.index

If it is possible can someone point me in right direction?

**Comment by schulzefelix** [comment]
At this point not, the package need some rewrite to access the new functions added by Google. This also causes this issue https://github.com/schulzefelix/laravel-search-console/issues/35
