### ISSUE TITLE
how can i get $token?

### ISSUE THREAD

**Issue by beatific-angel** [schulzefelix/laravel-search-console#39]
$data = SearchConsole::setAccessToken($token)->setQuotaUser('uniqueQuotaUserString')
        ->searchAnalyticsQuery(
            'https://www.example.com/',
            Period::create(Carbon::now()->subDays(30), Carbon::now()->subDays(2)),
            ['query', 'page', 'country', 'device', 'date'],
            [['dimension' => 'query', 'operator' => 'notContains', 'expression' => 'cheesecake']],
            1000,
            'web',
            'all',
            'auto'
        );

ErrorException
PHP 8.1.22
9.52.16
Undefined variable $token

how can i get $token?

**Comment by schulzefelix** [comment]
#13 see there
